module.exports = {
	arrowParens: "always",
	bracketSpacing: false,
	endOfLine: "lf",
	htmlWhitespaceSensitivity: "css",
	jsxBracketSameLine: false,
	jsxSingleQuote: false,
	printWidth: 80,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	semi: false,
	singleQuote: false,
	tabWidth: 1,
	trailingComma: "all",
	useTabs: true,
}
